# Generated by Django 4.2.3 on 2023-07-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("straight_neck_detector", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="hello",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="email",
                    ),
                ),
                ("password", models.CharField(max_length=255, verbose_name="password")),
                ("name", models.CharField(max_length=255)),
                ("is_employed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
