# Generated by Django 4.2.3 on 2023-07-08 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("straight_neck_detector", "0002_hello_users"),
    ]

    operations = [
        migrations.DeleteModel(
            name="hello",
        ),
    ]
